name: Add PR Description to Linear Issue

on:
  pull_request:
    types: [opened, edited]

jobs:
  add-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Post PR Description to Linear
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
        run: |
          ISSUE_ID=$(echo "${{ github.event.pull_request.title }}" | grep -oE 'LIN-[0-9]+')
          if [ -n "$ISSUE_ID" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $LINEAR_API_KEY" \
              -d "{\"issueId\": \"$ISSUE_ID\", \"body\": \"${{ github.event.pull_request.body }}\"}" \
              https://api.linear.app/graphql
          fi
